[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pystochastic"
version = "0.1.0"
description = "A Python library for stochastic processes and Monte Carlo simulation"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    {name = "Bastien Velcin"}
]

dependencies = [
    "numpy",
    "scipy",
    "plotly"
]

[tool.setuptools.packages.find]
where = ["."]